In [ ]:
import os
import ast
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

os.chdir("../")

In [ ]:
processed_data_path = "data/processed/responses_processed.csv"

In [ ]:
data = pd.read_csv(processed_data_path)

In [ ]:
unsuccessful_editing = data[
    (data["g"] == 5) & (data["c"].isin([7, 18]))
]

no_editing = data[
    ((data["g"] == 1) & (data["c"] == 15)) |
    ((data["g"] == 4) & (data["c"] == 8))  |
    ((data["g"] == 5) & (data["c"] == 13))
]

display(unsuccessful_editing[['age', 'LLM_use', 'LLM_impact', 'writing_style_pre', 'response_time_minutes', 'remarks']])

display(no_editing[['age', 'LLM_use', 'LLM_impact', 'writing_style_pre', 'response_time_minutes', 'remarks']])

,age,LLM_use,LLM_impact,writing_style_pre,response_time_minutes,remarks
90,35.0,Several times per week,LLM chatbots will have more negative than posi...,Somewhat,20.766667,NaN
101,53.0,Every day or almost every day,I have no opinion on the impact of LLM chatbot...,Not at all,37.033333,NaN

,age,LLM_use,LLM_impact,writing_style_pre,response_time_minutes,remarks
14,27.0,2-3 times in the past month,LLM chatbots will have more positive than nega...,Somewhat,7.450000,I thought the generated text was formal and su...
70,44.0,Every day or almost every day,LLM chatbots will have more positive than nega...,Somewhat,15.466667,NaN
96,34.0,Every day or almost every day,LLM chatbots will be very beneficial to society,Somewhat,11.100000,NaN